version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:latest
    container_name: mydox_db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=cikicheri75
      - MYSQL_PASSWORD=cikicheri75
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - PUID=0
      - PGID=0

  app:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: mydox
    restart: unless-stopped
    ports:
      - 8085:443
    links:
      - db
    volumes:
      - /mnt/mydox/config:/config
      - data:/data
    environment:
      - PUID=1002
      - PGID=1002
#      - MYSQL_PASSWORD=cikicheri75
#      - MYSQL_DATABASE=nextcloud
#      - MYSQL_USER=nextcloud
#      - MYSQL_HOST=db
      - TZ=Europe/Sofia
volumes:
  db:
    driver_opts:
      type: nfs
      o: addr=192.168.20.10,nfsvers=4
      device: :/mnt/Appz/Docker/Volumes/mydox/db
#  config:
#    driver_opts:
#      type: nfs
#      o: addr=192.168.20.10,nfsvers=4
#      device: :/mnt/Appz/Docker/Volumes/mydox/config
  data:
    driver_opts:
      type: nfs
      o: addr=192.168.20.10,nfsvers=4
      device: :/mnt/Appz/Docker/Volumes/mydox/data